#!/bin/bash
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO
 
 
do_start () {
 
    #/usr/bin/fbi -T 1 -noverbose -a /home/pi/splash.png
    # -o local for 3.5" headphones sound, -o hdmi sound
    audioconffile="/var/lib/alsa/asound.state"
    audioout="local"
    if [ -f  $audioconffile ]
    then
 
    #read the configuration
    straudio=$(sed -n "/PCM Playback Route/{N; /value ./p}" $audioconffile | grep value)
    #printf "straudio" $straudio
    audioconf=${straudio: -1}
    case "$audioconf" in
        0) audioout="hdmi"
        ;;
        1) audioout="local"
        ;;
        2) audioout="hdmi"
        ;;
        *) audioout="hdmi"
        ;;
    esac
    else
        printf "$audioconffile dos not exists"
    fi
    omxplayer -o $audioout /home/pi/splashvideo.mp4 &
    exit 0
}
 
case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac
 
:
