#! /bin/sh
### BEGIN INIT INFO
# Provides:          mvapifrontendconf
# Required-Start:    dbus
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Configure frontend at boot time
# Description:       Configure frontend at boot time
### END INIT INFO
 
 
do_start () {
 
    /home/pi/pifrontendconf.sh    
    exit 0
}
 
case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: apifrontendconf [start|stop]" >&2
    exit 3
    ;;
esac
 
:

